In [ ]:
print ('hi')

hi


In [ ]:
## a. Импортировать библиотеку NumPy
import numpy as np


In [ ]:
## b.Создайте массив из 10 нулей
array = np.zeros(10)
print ('10 nuley:')
print (array)

10 nuley:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
## c.Создайте массив из 10 единиц
array = np.ones(10)
print ('10 edenic:')
print (array)


10 edenic:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
## d. Создайте массив из 10 пятерок
array = np.ones(10)*5
print ('10 pyterok:')
print (array)

10 pyterok:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [ ]:
## e. Создайте массив целых чисел от 10 до 50
array = np.arange(10,51)
print ('ot 10 do 50')
print (array)

ot 10 do 50
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [ ]:
## f. Создайте массив четных чисел от 10 до 50
array = np.arange(10,51,2)
print ('chetnij ot 10 do 50')
print (array)

chetnij ot 10 do 50
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [ ]:
## g. Создайте матрицу 3x3 с числами от 0 до 8
matric = np.arange(0,9). reshape(3,3)
print (matric)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
## h. Создайте единичную матрицу 3х3
matric = np.eye(3)
print (matric)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
## i. Используй NumPy для генерации случайных чисел от 0 до 1
rand = np.random.rand(25)
print (rand)

[0.38854714 0.52732949 0.15088821 0.47395354 0.92654934 0.68716586
 0.37968587 0.76638295 0.75671583 0.07661775 0.11570083 0.69158512
 0.0494887  0.32086396 0.33763349 0.45311015 0.51078096 0.16336328
 0.67008344 0.58491045 0.12959671 0.7517548  0.00423408 0.29060998
 0.5349492 ]


In [ ]:
## j. Используй NumPy сгенерировать массив из 25 случайных чисел,взято из стандартного нормального распределения
matric = np.random.normal(0,1,25)
print (matric)

[ 0.09113205 -0.70190016  0.61049855  0.98034282  0.01584976 -0.75406255
 -2.3258774  -0.04823825  0.97998049 -0.20057008 -1.23100001 -1.47997847
  0.6520686   1.47912079  0.93144686 -0.43167634  0.35843294  0.61425294
  0.26680109 -0.99812162 -0.40191622 -0.94651799 -0.45360552 -0.39144237
 -1.10470258]


In [ ]:
## k.Создайте следующую матрицу, используя библиотеки функций Числов
matric = np.arange(0,01.01,0.01)
print (matric)


[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41
 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55
 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69
 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83
 0.84 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97
 0.98 0.99 1.  ]


In [ ]:
## l. это наша начальная матрица, вернуть код из стартовой
mat = np.arange(1,26).reshape(5,5)
print (mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
print ('l=',mat[2:,1:]) 

l= [[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [ ]:
## m. Написать код обращения к элементу, который вернет значение 20 из стартовой матрицы задачи l
m = mat[mat == 20]
print (m)

[20]


In [ ]:
 ## n. Написать код к стартовой матрицы задачи l, который воспроизводит вывод показанный ниже
print ('array =' , mat[0:3,1]. reshape(3,1))


array = [[ 2]
 [ 7]
 [12]]


In [ ]:
## o. Написать код к стартовой матрице задачи l , который воспроизводит вывод, показанный ниже
print ('array =' , mat[4:])

array = [[21 22 23 24 25]]


In [ ]:
## p. Написать код к стартовой матрице задачи l , который воспроизводит вывод, показанный ниже
print ('array =' , mat[3:])

array = [[16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
## q. Получить сумму всех значений в стартовой матрице mat
print (mat.sum())

325


In [ ]:
## r. Получить стандартное отклонение в стартовой матрице mat
print (mat.std())

7.211102550927978


In [ ]:
## s. Получить сумму значений в колонках в стартовой матрице mat
print (mat.sum(axis=0))

[55 60 65 70 75]
